import TopHeader from "./components/TopHeader";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Montserrat } from "next/font/google";



import type { Metadata } from "next";
 import localFont from "next/font/local";
import "./globals.css";


const montserrat = Montserrat({

  subsets: ['latin'], 
  weight: ['400', '700'], 
});
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <TopHeader/>
        <Header/>
         
     
        {children}

        
        <Footer/>
        </body>
    </html>
  );
}
